ERROR - 2024-01-19 03:41:34 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itc', 3306, '', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV063...')
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV063...')
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#11 {main}
CRITICAL - 2024-01-19 03:41:34 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `token` = :token:', [...], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV0634OPEl8uaAvUexIzJLwMkGBSYmTjgNFt9pio')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 03:41:38 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itc', 3306, '', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(469): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getOrder()
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(469): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getOrder()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#11 {main}
CRITICAL - 2024-01-19 03:41:38 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `orders`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\MainController.php(469): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->getOrder()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 03:41:42 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itc', 3306, '', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(665): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getNotif()
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(665): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getNotif()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#11 {main}
CRITICAL - 2024-01-19 03:41:42 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `notif`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\MainController.php(665): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->getNotif()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 03:41:46 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itc', 3306, '', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV063...')
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV063...')
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#11 {main}
CRITICAL - 2024-01-19 03:41:46 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `token` = :token:', [...], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV0634OPEl8uaAvUexIzJLwMkGBSYmTjgNFt9pio')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 03:41:51 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itc', 3306, '', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV063...')
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV063...')
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#11 {main}
CRITICAL - 2024-01-19 03:41:51 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `token` = :token:', [...], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV0634OPEl8uaAvUexIzJLwMkGBSYmTjgNFt9pio')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 03:41:55 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itc', 3306, '', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(665): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getNotif()
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(665): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getNotif()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#11 {main}
CRITICAL - 2024-01-19 03:41:55 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `notif`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\MainController.php(665): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->getNotif()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 03:41:59 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itc', 3306, '', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(469): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getOrder()
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(469): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getOrder()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#11 {main}
CRITICAL - 2024-01-19 03:41:59 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `orders`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\MainController.php(469): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->getOrder()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 03:42:03 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itc', 3306, '', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV063...')
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV063...')
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#11 {main}
CRITICAL - 2024-01-19 03:42:03 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `token` = :token:', [...], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV0634OPEl8uaAvUexIzJLwMkGBSYmTjgNFt9pio')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 03:42:07 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itc', 3306, '', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV063...')
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV063...')
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#11 {main}
CRITICAL - 2024-01-19 03:42:07 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `token` = :token:', [...], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV0634OPEl8uaAvUexIzJLwMkGBSYmTjgNFt9pio')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 03:42:11 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itc', 3306, '', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(665): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getNotif()
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(665): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getNotif()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#11 {main}
CRITICAL - 2024-01-19 03:42:11 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `notif`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\MainController.php(665): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->getNotif()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 03:42:16 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itc', 3306, '', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(469): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getOrder()
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(469): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getOrder()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#11 {main}
CRITICAL - 2024-01-19 03:42:16 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `orders`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\MainController.php(469): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->getOrder()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 03:42:20 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itc', 3306, '', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV063...')
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\capstone_backend\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\capstone_backend\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV063...')
#7 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#11 {main}
CRITICAL - 2024-01-19 03:42:20 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `token` = :token:', [...], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\MainController.php(393): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->getUserData('fyHhKnDWR2qV0634OPEl8uaAvUexIzJLwMkGBSYmTjgNFt9pio')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 06:37:21 --> mysqli_sql_exception: Column 'second_image' cannot be null in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `re...', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `re...')
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `re...')
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `re...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capstone_backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\capstone_backend\system\BaseModel.php(698): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(812): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->save_ratings()
#10 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#11 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2024-01-19 06:37:21 --> Column 'second_image' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `review` (`prod_name`, `product_id`, `comment`, `rate`, `first_image`, `second_image`, `third_image`, `isAnonymous`) VALUES (:prod_name:, :product_id:, :comment:, :rate:, :first_image:, :second_image:, :third_image:, :isAnonymous:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(698): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\MainController.php(812): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->save_ratings()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 06:37:33 --> mysqli_sql_exception: Column 'second_image' cannot be null in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `re...', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `re...')
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `re...')
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `re...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capstone_backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\capstone_backend\system\BaseModel.php(698): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(812): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->save_ratings()
#10 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#11 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2024-01-19 06:37:33 --> Column 'second_image' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `review` (`prod_name`, `product_id`, `comment`, `rate`, `first_image`, `second_image`, `third_image`, `isAnonymous`) VALUES (:prod_name:, :product_id:, :comment:, :rate:, :first_image:, :second_image:, :third_image:, :isAnonymous:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(698): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\MainController.php(812): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->save_ratings()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
CRITICAL - 2024-01-19 06:41:49 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 1726.
 1 SYSTEMPATH\BaseModel.php(1726): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\BaseModel.php(748): CodeIgniter\BaseModel->transformDataToArray([], 'insert')
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([], true)
 4 APPPATH\Controllers\MainController.php(799): CodeIgniter\Model->insert([])
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->saveRatings()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 06:52:42 --> mysqli_sql_exception: Column 'prod_name' cannot be null in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `re...', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `re...')
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `re...')
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `re...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capstone_backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(806): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#13 {main}
CRITICAL - 2024-01-19 06:52:42 --> Column 'prod_name' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `review` (`prod_name`, `product_id`, `comment`, `rate`, `first_image`, `second_image`, `third_image`, `isAnonymous`) VALUES (:prod_name:, :product_id:, :comment:, :rate:, :first_image:, :second_image:, :third_image:, :isAnonymous:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(806): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 06:57:26 --> mysqli_sql_exception: Column 'prod_name' cannot be null in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `re...', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `re...')
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `re...')
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `re...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capstone_backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(807): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#13 {main}
CRITICAL - 2024-01-19 06:57:26 --> Column 'prod_name' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `review` (`prod_name`, `product_id`, `comment`, `rate`, `first_image`, `second_image`, `third_image`, `isAnonymous`) VALUES (:prod_name:, :product_id:, :comment:, :rate:, :first_image:, :second_image:, :third_image:, :isAnonymous:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(807): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 07:00:21 --> mysqli_sql_exception: Column 'prod_name' cannot be null in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `re...', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `re...')
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `re...')
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `re...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capstone_backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(808): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#13 {main}
CRITICAL - 2024-01-19 07:00:21 --> Column 'prod_name' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `review` (`prod_name`, `product_id`, `comment`, `rate`, `first_image`, `second_image`, `third_image`, `isAnonymous`) VALUES (:prod_name:, :product_id:, :comment:, :rate:, :first_image:, :second_image:, :third_image:, :isAnonymous:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(808): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 07:07:30 --> mysqli_sql_exception: Column 'second_image' cannot be null in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `re...', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `re...')
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `re...')
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `re...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capstone_backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(808): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#13 {main}
CRITICAL - 2024-01-19 07:07:30 --> Column 'second_image' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `review` (`prod_name`, `product_id`, `comment`, `rate`, `first_image`, `second_image`, `third_image`, `isAnonymous`) VALUES (:prod_name:, :product_id:, :comment:, :rate:, :first_image:, :second_image:, :third_image:, :isAnonymous:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(808): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 07:07:36 --> mysqli_sql_exception: Column 'second_image' cannot be null in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `re...', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `re...')
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `re...')
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `re...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capstone_backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(808): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#13 {main}
CRITICAL - 2024-01-19 07:07:36 --> Column 'second_image' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `review` (`prod_name`, `product_id`, `comment`, `rate`, `first_image`, `second_image`, `third_image`, `isAnonymous`) VALUES (:prod_name:, :product_id:, :comment:, :rate:, :first_image:, :second_image:, :third_image:, :isAnonymous:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(808): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 07:07:39 --> mysqli_sql_exception: Column 'second_image' cannot be null in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `re...', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `re...')
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `re...')
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `re...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capstone_backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(808): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#13 {main}
CRITICAL - 2024-01-19 07:07:39 --> Column 'second_image' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `review` (`prod_name`, `product_id`, `comment`, `rate`, `first_image`, `second_image`, `third_image`, `isAnonymous`) VALUES (:prod_name:, :product_id:, :comment:, :rate:, :first_image:, :second_image:, :third_image:, :isAnonymous:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(808): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 07:33:08 --> mysqli_sql_exception: Column 'comment' cannot be null in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `re...', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `re...')
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `re...')
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `re...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capstone_backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(818): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#13 {main}
CRITICAL - 2024-01-19 07:33:08 --> Column 'comment' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `review` (`prod_name`, `product_id`, `comment`, `rate`, `isAnonymous`) VALUES (:prod_name:, :product_id:, :comment:, :rate:, :isAnonymous:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(818): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
ERROR - 2024-01-19 07:33:11 --> mysqli_sql_exception: Column 'comment' cannot be null in C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\capstone_backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `re...', 0)
#1 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `re...')
#2 C:\laragon\www\capstone_backend\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `re...')
#3 C:\laragon\www\capstone_backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `re...', Array, false)
#4 C:\laragon\www\capstone_backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capstone_backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capstone_backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\capstone_backend\app\Controllers\MainController.php(818): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\capstone_backend\system\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
#9 C:\laragon\www\capstone_backend\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\capstone_backend\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\capstone_backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\capstone_backend\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#13 {main}
CRITICAL - 2024-01-19 07:33:11 --> Column 'comment' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `review` (`prod_name`, `product_id`, `comment`, `rate`, `isAnonymous`) VALUES (:prod_name:, :product_id:, :comment:, :rate:, :isAnonymous:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(818): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\MainController->submitReview()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\capstone_backend\\public\\index.php')
